Pin encoding into aeser
aeternity/aeserialization pull request #24
Opened 2024-12-12 17:35 UTC by klercker

Moved the pin encoding/decoding methods from core to serialization. A follow-up PR will be done post merge for the corresponding refactoring in `aeternity/aeternity`

This pull request is supported by the Æternity Foundation.

2024-12-13 08:51 UTC, hanssv requested changes
Moving this to aeserialization is 100% the right move 👍 

But, I would like this to be less prominent, i.e. in a separarte module. And it should be made much more clear that this is HyperChains stuff!

2024-12-13 09:14 UTC, klercker commented
So, proposing to do this:
1. introduce `aeser_hc.erl`module
2. Move the methods there
...and then we have ourselves a merry little Christmas 🎄 (in a week of course...)

2024-12-13 10:32 UTC, hanssv approved these changes, later dismissed

2024-12-13 10:32 UTC, hanssv commented on src/aeser_hc.erl
> +%%% Module for various Hypoerchain-related encoding tasks
```suggestion
%%% Module for various Hyperchains-related encoding tasks
```

2024-12-13 11:01 UTC, hanssv submitted a review, later dismissed

2024-12-13 13:10 UTC, richcarl approved these changes

2024-12-13 14:01 UTC, hanssv approved these changes

2024-12-16 05:31 UTC, ThomasArts approved these changes

2024-12-16 08:59 UTC, merged